import iec from "../assets/images/iec.png";

export const products = {
  basmati: {
    label: "Basmati",
    items: [
      {
        id: 1,
        title: "1121 Basmati Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 2,
        title: "1121 Basmati Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 3,
        title: "1121 Basmati Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 4,
        title: "1121 Basmati Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 5,
        title: "1718 Basmati Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 6,
        title: "1718 Basmati Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 7,
        title: "1718 Basmati Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 8,
        title: "1718 Basmati Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 9,
        title: "1509 Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 10,
        title: "1509 Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 11,
        title: "1509 Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 12,
        title: "1401 Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 13,
        title: "1401 Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 14,
        title: "1401 Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 15,
        title: "Pusa Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 16,
        title: "Pusa Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 17,
        title: "Pusa Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 18,
        title: "Pusa Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 19,
        title: "Traditional Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 20,
        title: "Traditional Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
    ],
  },

  nonBasmati: {
    label: "Non-Basmati",
    items: [
      {
        id: 101,
        title: "Sugandha Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 102,
        title: "Sugandha Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 103,
        title: "Sugandha Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 104,
        title: "Sugandha Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 105,
        title: "Sharbati Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 106,
        title: "Sharbati Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 107,
        title: "Sharbati Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 108,
        title: "Sharbati Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 109,
        title: "PR 11/14 Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 110,
        title: "PR 11/14 Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 111,
        title: "PR 11/14 Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 112,
        title: "PR 11/14 Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 113,
        title: "PR 47 Raw",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 114,
        title: "PR 47 Steam",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 115,
        title: "PR 47 Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
      {
        id: 116,
        title: "PR 47 Golden Sella",
        image: iec,
        details: {
          grainLength: "6.8 mm",
          moisture: "12%",
          broken: "2%",
          origin: "India",
          packing: "5kg / 25kg / 50kg",
        },
      },
    ],
  },
};
